name: Official Build

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Restore dependencies in ReferenceCop.Package
      run: dotnet restore
      working-directory: src/ReferenceCop.Package
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/ReferenceCop.Package
      
    - name: Run Tests in ReferenceCop.Tests
      run: dotnet test --verbosity normal
      working-directory: src/ReferenceCop.Tests

    - name: Run Tests in ReferenceCop.Roslyn.Tests
      run: dotnet test --verbosity normal
      working-directory: src/ReferenceCop.Roslyn.Tests

    - name: Run Tests in ReferenceCop.MSBuild.Tests
      run: dotnet test --verbosity normal
      working-directory: src/ReferenceCop.MSBuild.Tests

    - name: Set NuGet Package Version Environment Variable from tag (only for tagged builds)
      if: ${{ github.ref_type == 'tag' }}
      run: echo "PKGVERSION=${{ github.ref_name#'v' }}" >> $env:GITHUB_ENV

    - name: Display NuGet Package Version Environment Variable (only for tagged builds)
      if: ${{ github.ref_type == 'tag' }}
      run: echo "version $env:PKGVERSION"

    - name: Publish NuGet Package (only for tagged builds)
      if: ${{ github.ref_type == 'tag' }}
      run: |
        dotnet pack --configuration Release --no-build --output nupkgs /p:PackageVersion=$env:PKGVERSION
        dotnet nuget push **/nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: src/ReferenceCop.Package
